### ISSUE TITLE
Adding object type prefix

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#11]
For example,
Component: _c-btn ...
Utility: _u-text--right ...

**Comment by torounit** [comment]
flocss的には必須要素では無いんですよね。
gridをどこに入れるかとかは結構微妙なところです。

**Comment by inc2734** [comment]
クラス名のうっかり重複の可能性をできるだけ減らしたいのでつけようと思ったのですが、フレームワークのprefixもつくので冗長ですかねぇ。gridはこれ以上長くしたくないのでそのままのつもりです。
