### ISSUE TITLE
Semantic Versioning

### ISSUE THREAD

**Issue by torounit** [inc2734/basis#15]
後方互換性を破壊する変更（ class の削除、命名の変更 ）は、バージョン番号の一桁目を変更すべき。
二桁目は、機能追加。
三桁目は、機能に変更がない修正。（バグフィックスなど）

npmでアップデートしたりしたときに事故る。

**Comment by inc2734** [comment]
ひー (@@;

**Comment by torounit** [comment]
とりあえず、次期バージョンは 2.0.0 ですかね

**Comment by torounit** [comment]
https://github.com/inc2734/basis/commit/e4fd26837a9590ee443fb7da145bbe41d266375e
