### ISSUE TITLE
Separate the foundation/_base.scss

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#16]
実際にサイト制作するときに、_base.scss で定義されたスタイルは邪魔になりそう。基本は normalize.css だけにして、_base.scss はテーマ CSS の1つとして分離するほうが良い気がする。

**Comment by torounit** [comment]
https://github.com/inuitcss 
みたいにするのも一つの道。

もともとSassで個別に Import 出来るので別に良いのかなーとも思います。
ただ、base は typography と heading とかには分けた方が良いのかも。

**Comment by inc2734** [comment]
Basis は最終的には WordPress のテーマ制作に使うのが目的なので、_base を簡単にオンオフしたり別の base に切り替えれるようにしたいんですよね。

**Comment by torounit** [comment]
微妙くさいですね。CSSはどうしても要素セレクタに依存するので、それを外部に出しちゃうとつらいかも。
オーバーライドしやすいセレクタ設計をする方がベターなアプローチな気がします。（現状だとh1 ~ h6 の:first-childがたぶんつらい）

**Comment by inc2734** [comment]
うーんやっぱり微妙ですかねぇ…。Basis 自体にタイポグラフィの CSS が不要なのと、normalizeをさらに上書きってのがなんか気持ち悪いんですけど、それを解決する良いアイデアが思いつかない…。

:first-child はやっぱりそうですか。どうせやるやろと思いましたが、これはフレームワークの仕事では無い気がしますね。

**Comment by torounit** [comment]
normalizeはリセットと言うよりは、あくまでブラウザのギャップを埋めてくれる互換レイヤーです！
