### ISSUE TITLE
Rename col classes.

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#21]
._row__col--1-2 ではなく、._row__col--1of2 のほうがわかりやすいのではないか？

**Comment by torounit** [comment]
Yahoo製のpureなんかは 1-2形式ですね。個人的には1of2の方が好きですが、英語の意味合い的に微妙っぽい。

**Comment by torounit** [comment]
なので 1-2に +1

**Comment by inc2734** [comment]
もともと pure を参考にしてますw 1of2 って英語的に変なのですね。何かのフレームワークで見ていけるやんって思ったのですが、それではひとまず 1-2 のままにしておきたいと思います。情報ありがとうございます！

**Comment by torounit** [comment]
1/3 とかだと、one third なんですよね。1of3とかだと3つの中の一つみたいな感じにだったはず。
1/3とかが4つ続いたりとかがあり得るので、ちょっと変ってことっぽい。
