### ISSUE TITLE
Gird is Components?

### ISSUE THREAD

**Issue by torounit** [inc2734/basis#22]
https://github.com/hiloki/flocss
フレームワークとして提供するなら、コンポーネントレイヤーにした方が良いと思う。
「ProjectレイヤーがComponentレイヤーのモジュールを変更すること」のみが許可されているので。

**Comment by inc2734** [comment]
FLOCSS のページにも

> 
これらをクラスとして扱う場合には、それらは Object/Componentレイヤーとして定義させるほうが、多くのレイアウト、グリッドフレームワークをFLOCSSに適用させやすいと考えています。

とありますね。グリッドシステムのクラスにも c- がつくのは何となくイヤなのですが、そのほうが良さそうなのであれば移したほうが良いですかね
