### ISSUE TITLE
assets dir はいらない

### ISSUE THREAD

**Issue by torounit** [inc2734/basis#27]
フレームワークなので、レポジトリ直下にsrcもしくはcssとかって置くべき。

**Comment by torounit** [comment]
この場合scssか

**Comment by torounit** [comment]
assetsに入るべきはこの場合、ドキュメントのみで使う画像とかですかね。

**Comment by inc2734** [comment]
そういうものなんですね。確かに Foundation や Pure をみると assets ってないですね。Bootstrap はちょっと違いましたが。ドキュメントも直下に index.html ではなくて doc みたいなディレクトリに入れようかなと考えています。

**Comment by torounit** [comment]
それだとgh-pagesめんどくない？

**Comment by inc2734** [comment]
はい、めんどそうなので手を付けてないですw

**Comment by torounit** [comment]
Please merge!

**Comment by inc2734** [comment]
assets が何もかもなくなってるっぽい気がするのですが大丈夫ですかね…？
https://github.com/torounit/basis/tree/2952cf63472e67d4b79f9843e86b82d9f7cf22dc

**Comment by torounit** [comment]
だめですだめですだめですすみませんcloseしました。
