### ISSUE TITLE
npm 経由でとってきたときに npm 3でnormalizeがバグる。

### ISSUE THREAD

**Issue by torounit** [inc2734/basis#28]
node_modulesのディレクトリ構造が変わったため。

**Comment by torounit** [comment]
gulpを魔改造するよりはあきらめてnormalizeをバンドルした方がよさそう。orz

**Comment by inc2734** [comment]
わーそうなんですね。更新めんくさいのですごく良いなーと思っていたのですが。。

**Comment by torounit** [comment]
gulpでなんかタスク書けば良いんですけどね。
あとは npm2 を使う人が減れば。。。

**Comment by torounit** [comment]
とりあえず close

**Comment by torounit** [comment]
#38 でも同じようにできるはず。
