### ISSUE TITLE
/index.html -> /doc/index.html

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#31]
I feel this is more clean directory structure. But I feel github pages is hard.

**Comment by torounit** [comment]
開発中は、build みたいなディレクトリ作って、そこにhtmlとcss放り込むようにしますか。

**Comment by inc2734** [comment]
一応 doc の中が更新されるようにしたつもりですが、分けたほうが良さそうな感じですかね？

**Comment by torounit** [comment]
監視が面倒かなぁと。
あとは、https://github.com/google/web-starter-kit/blob/master/gulpfile.babel.js#L177

みたいな手もあるけど・・・

**Comment by torounit** [comment]
というかさっきプルしたのでチョット今レビュー中

**Comment by torounit** [comment]
あ、でもシンプルで良いと思います！一応明日の朝九時までなら1/31よね！

**Comment by inc2734** [comment]
あんまり日付にこだわりないので1/31でなくても良いです^^;

**Comment by torounit** [comment]
とりあえず、npm 2 と npm 3でテストしてきます。

これTravisでやりたいねぇ。
