### ISSUE TITLE
npm 3 build error on npm install.

### ISSUE THREAD

**Issue by torounit** [inc2734/basis#37]
> /path/to/project
> └── (empty)
> 
> npm ERR! code 1

**Comment by torounit** [comment]
そもそもnpm 3 だとビルドが無くてもこける。

**Comment by inc2734** [comment]
npm3 に対応していないモジュールがあるとかですかね？それだとこちら側では解決できなそうなのでとりあえず放置…？

**Comment by inc2734** [comment]
Node.js 4.2.1、npm 3.6.0 で npm install と gulp の実行できました。@torounit さんのバージョンってどうなってますか？

**Comment by quwahiro** [comment]
おつかれさまです。
npm3ビルドできました。
node 5.5.0

npm@3 
npm 3.6.0

念のためにこのあと戻してnpm@2でもやってみました。
npm@2
npm@2.14.17

**Comment by torounit** [comment]
えーと、正確には、普通にgit clone すると出来るんですが、
`
{
  "private": "true",
  "dependencies": {
    "basis": "inc2734/basis#develop"
  }
}

`
等で外部のnpm モジュールとしてとってきた場合、ビルドというか node_modules のインストールに失敗するんですね。npm 2 なら大丈夫なんですが。

**Comment by quwahiro** [comment]
あ、再現できました。
ほんとねー。

**Comment by quwahiro** [comment]
そしてエラーさえもでなくなった。。。
![2016-02-04 17 29 02](https://cloud.githubusercontent.com/assets/746995/12809750/e92f6222-cb64-11e5-91ad-cb17a9286bae.png)

**Comment by torounit** [comment]
npm 3系は 3.3, 3.4, 3.6 それぞれでやってそれぞれでこけました。
ビルドタスクはgulpに依存するのはやめて、CLI直接たたくのが良いかもです。
node-sass から post-cssで autoprefixer かませて、それをminifyすれば良いだけでしょう？w

**Comment by inc2734** [comment]
僕にはおてあげです！！よろしく！

**Comment by torounit** [comment]
> npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
> npm WARN deprecated lodash@1.0.2: lodash@<2.0.0 is no longer maintained. Upgrade to lodash@^3.0.0

ってエラーが出てこけるんですが、これ gulp をdevDependencies にしてもだめでした。

**Comment by torounit** [comment]
だれだよー。ビルド自動化して配信すべき！とか言ってプルリク投げた奴・・・

**Comment by torounit** [comment]
なんか、dependencies に basis と書いていたのが原因くさいです。
`
{
  "private": "true",
  "dependencies": {
    "sass-basis": "inc2734/basis#develop"
  }
}
`

**Comment by quwahiro** [comment]
ま、まじで！
