### ISSUE TITLE
IE9 Support

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#40]
IE9 でも最低限のレイアウトは維持できるようにグリッドシステムを IE9 に対応させたい。
参考：FOX-CSS https://github.com/ronanlevesque/FOX-CSS/blob/master/sass/_grid-ie9.scss
要件によっては不要なので、プラグインっぽく別 CSS にわけたい。

**Comment by quwahiro** [comment]
引数渡して、
gulp build -with ie9
でstyle.scssに @import "ie9"を追加するってどうです？

**Comment by inc2734** [comment]
後々 WordPress のテーマに含めるつもりで開発しているので、もともとユーザーにビルドさせて使うという想定ではないんですよね。となると、_ie9.scss としてしまうのは都合が悪くて。ie9.css をこうすれば basis.css と結合できます、というマニュアルはあると良いかもしれません。

**Comment by quwahiro** [comment]
PHP側でファイル結合でもいいかもですね。
gulp側で需要はありますか？
>マニュアル
gulp build -h でヘルプ出したい。

**Comment by inc2734** [comment]
そこまでするとめんどくさそうなので、/doc/ のページに説明を入れるので良いかなと。結合は PHP だと静的な場合にアウトになってしまうので gulp が良いですね。@import '〜' 等々追加すれば結合できますみたいな。

**Comment by torounit** [comment]
別レポジトリにして、basisをオーバーライドするようなものが良いんじゃ無いかと。積極的サポートするわけでもないのでいろいろ面倒も多いかと。

もしくは https://10up.github.io/flexibility/ でごまかすとか？

**Comment by inc2734** [comment]
一応別レポジトリにはするつもりでいます。いまちょっと実戦テスト中で、IE9 以上対応が必要なのでそこで作ってしまおうかなと。display: inline-block と width の組み合わせで基本的な段組だけはできそうだったので。js 使うとはまったときに対処が大変そうなので css で基本的な部分だけサポートというのが良いと思っています。

**Comment by torounit** [comment]
display: inline-block のGrid って HTMLに改行入れるとバグったりしない？

**Comment by inc2734** [comment]
試した感じ、改行の有無でおかしくなってる感じはなかったですが、カラム幅がぴったりの割合（例えば 50% + 50% ）だとカラム落ちしちゃいました…。上下位置の指定ができるので float より良いと思ったんですけどちょっと悩みますね。

**Comment by inc2734** [comment]
あ、改行分空白が開くからですね

**Comment by inc2734** [comment]
まさにこれ！ http://hiloki.github.io/kitecss/

**Comment by torounit** [comment]
グリッドの親でfont-size 0 にしてるという奴ですね。
フォントサイズの継承関係がおかしくなるというところに目をつぶればいけますね。

bodyに当てるfont-size を変数にしておいて、それを col に適用するとかいう実装ならそれほど大きな影響にはならないかと思います。
