### ISSUE TITLE
col の中身が大きいと段組が崩れることがある。

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#42]
._c-row__col に overflow: hidden をつければ防止できるけど、わざと要素をはみ出させたいとかができなくなるので悩みどころ…。

**Comment by torounit** [comment]
max-width を同時につけるとboxそのものは広がらないですね。

**Comment by inc2734** [comment]
おー！そんな手があるのですね。そのほうが良さそうですね。その場合、flex-basis での幅指定って必要なんですかね…？軽くテストしてみたところ max-width があれば flex-basis はなくても大丈夫っぽかったですが。

**Comment by torounit** [comment]
flex-basis は入れておくべき！ある意味 ハックみたいなものなので・・・。

**Comment by inc2734** [comment]
なるほど！いまいち flex-basis がよくわからないんですよね。width でもええやん感もあるし…。残してmax-width 足す方向でいきますね。アドバイスありがとうございます。

**Comment by torounit** [comment]
flex 用の width と考えればだいたい合ってます。

**Comment by inc2734** [comment]
max-width 追加しないと IE では普通に崩れますね。border とか padding とかあるとダメみたいです。ボックスモデルの解釈が変なのかな…

**Comment by torounit** [comment]
IEだと割り切れない場合とかの処理がおかしくなったりした記憶があります。

**Comment by inc2734** [comment]
これっぽかったです。
https://github.com/philipwalton/flexbugs#7-flex-basis-doesnt-account-for-box-sizingborder-box
