### ISSUE TITLE
._row__col--flex

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#45]
._row__col--flex は用途的に子の高さを全て揃えたいときに使うことがほとんどだと思うので、._row--flex にしたほうが良いのではないか。

**Comment by torounit** [comment]
+1
--flex というよりはなんかもっと高さをそろえる的な名前がいい気がします。

**Comment by inc2734** [comment]
--max-height, --fill, --stretch, --grow うーん

**Comment by torounit** [comment]
--eq-height ? なんか冗長な気もするけど

**Comment by inc2734** [comment]
よくよく考えると高さだけが広がるわけではなく、そのカラム内で上下左右いっぱいに広がるわけなので、height とかはつけずに、--fill でいこうと思います。

**Comment by torounit** [comment]
+1
