### ISSUE TITLE
npm モジュールでとってきたものを import sass するとやっぱりエラー。

### ISSUE THREAD

**Issue by torounit** [inc2734/basis#51]
init-normalize がエラー。
normalizeをimportするのでは無く、copy するような実装に変えた方がいいやもしれぬ。

**Comment by torounit** [comment]
sass版にはnormalize 同梱しないとか・・・？

**Comment by inc2734** [comment]
```
$ git clone git@github.com:inc2734/basis.git
$ git checkout -b develop
$ git pull origin develop
$ npm install
$ gulp
```

とやると普通にビルドできたのですが、僕の再現手法が間違っているか、前の issue であったような npm のバージョンの問題ですか？

**Comment by torounit** [comment]
npm 経由でとってくると、normalizeをとってくるときにばぐるっぽいです

**Comment by inc2734** [comment]
node@4.2.1、npm@3.6.0 で
`
npm install "git://github.com/inc2734/basis.git#develop"
`
でインストールできましたが、コマンドあってますかね…？

**Comment by torounit** [comment]
説明が悪いですね。

```
npm install "git://github.com/inc2734/basis.git#develop"
```

でとってきた basis に対して、

```scss
@import "../node_modules/sass-basis/src/scss/basis"
```
等とした場合、その Sass を普通にコンパイルした場合、node_modules からとってきている、normalize.scss が見つからん！というエラーを吐きます。

ユーザー側で、普通に gulp 等で、sass をコンパイルすると、sass-module-importer 等をインストールして設定してもらえれば解決するんですが、それはどうなのよ・・・・。というはなしです。

**Comment by inc2734** [comment]
あーなるほど理解しました。sass-module-importer がないと `@import "inuit-normalize";` では勝手に node_modules の中から normalize をインポートできないわけですね。だからといって相対パスに書き直すと、2系と3系でパスが変わるから NG と。npm install したときに自動ビルド走るので、その中で npm 経由の normalize をコピーするようにすれば行けそうな気がしますが、すごくめんどくさそうなので最初から含めたほうがよくね？ということですね…。

**Comment by inc2734** [comment]
https://github.com/inc2734/basis/commit/a43f8eb63c5e0942b35402197fabfe3ea656085a で僕の環境ではビルドできましたが、@torounit さんの環境でもビルドできますか？

**Comment by torounit** [comment]
git clone してきた場合、問題なかったです。

package.jsonに書いて実行した場合、npm install 時
node 5.5, npm 3.7 ではビルドできました。
ですが、 node 4.2.3 npm 2.14.7 だとエラーこきます。(たいした情報は無い) その後、もう一度 npm install するとビルドできます。。。

**Comment by inc2734** [comment]
おぉ、今度は2系でダメですか…。もう一度やるとビルドできるのであればもうこれでマージしちゃおうかな。。

**Comment by torounit** [comment]
それ怒られる奴！

**Comment by inc2734** [comment]
(TT) 良い方法だと思ったんですけどね…。 安全なのは同梱ですかねー。Foundation や Bootstrap も同梱してるようですし。

**Comment by torounit** [comment]
いや、これは！とは思ったんですがね。まぁ、バージョンが上がれば消滅する問題っぽいので、それまでは同梱してもいいのかなーとは。やり方自体は散々やったのでいつでも復活させらさますしw
