### ISSUE TITLE
GridのClassの命名が微妙かも。

### ISSUE THREAD

**Issue by torounit** [inc2734/basis#7]
_row, _col となっているが、基本的には、
    
__\_rowの直下の子要素に_colが来る__

という使い方以外はしないはずなので、であれば、_row__col のようなElementとして命名すべきかと。

**Comment by inc2734** [comment]
頻繁に使うクラスだから長くしたくないなと思ってそうしていたのですが、確かにそこだけ統一されていないというのもおかしいですね。修正しようと思います。
