### ISSUE TITLE
Refactoring variable, function, mixin layer.

### ISSUE THREAD

**Issue by inc2734** [inc2734/basis#75]
サイト全体で管理するべきグローバル変数・関数と、その場だけで良いローカルな変数・関数を整理したい。ミックスインもファイル構成を整理する（できれば #48 も可能なように）

**Comment by inc2734** [comment]
ミックスインはそれぞれ独立して使えるように、変数は !default でもっておき、Basis で中で使うときはデザインのバランスが崩れないように Basis のグローバル変数で上書きする形が良いかも。

**Comment by torounit** [comment]
+1

**Comment by inc2734** [comment]
とりあえずのアーキテクチャ案。

- /basis-setting [各コンポーネントの変数を上書きする変数]
	- _basis-setting.scss
	- _typography.scss
	- etc...
- /require [Basis の各コンポーネントに必須の関数・ミックスイン]
	- /function
	- /mixin
- /mixin [各コンポーネントの実体。ミックスインライブラリとして利用できる用]
	- /object
		- /component
		- /utility
- /class [CSS フレームワークとして動作させるための各クラス]
	- /foundation
	- /object
		- /component
		- /utility
- basis.scss

**Comment by inc2734** [comment]
/require とか作っちゃったら結局そこまでモジュラブルじゃなくない…。変数も /require に入れちゃいたくなるし。それならいっそ /require 無くして /basis-setting に /function、/mixin を入れて各コンポーネントで変数とかミックスイン使ってる部分全てローカル変数かしたほうが良さそう。変数の二重定義がくそめんどくさいのが問題。

**Comment by torounit** [comment]
そもそもこれ大まじめにやるなら、sassのmixin集は別に切り出してCSSの設計とは別のレイヤーとして考えた方が良いかも。

**Comment by inc2734** [comment]
CSS フレームワーク、Sass ミックスインライブラリ、各モジュールの単体利用、どのパターンでも使えるようにしようとすると必ずどこかで重複がでてくるので管理が大変ですね。Bourbon の設計とかも参考にしてみたいと思います。考えているうちによくわからなくなってきました…。

**Comment by torounit** [comment]
http://refills.bourbon.io/ に至るまでのアプローチは綺麗ですねぇ。
Mixin自体はセレクターに依存しないはず。ということはCSSのアーキテクチャーとは別物！って開き直るとわかりやすいのかなーどうなのかなー

**Comment by inc2734** [comment]
僕的には便利ミックスインを提供する気は全然なくて、各コンポーネントのスタイルをオリジナルのクラス名で使いたいとか、単独のコンポーネントだけ取り出して使いたい、とかを想定しているので、そのへんて設計に違いが出てくるかなとは思います。（その想定の需要あるの？な気はしてきる…）

**Comment by inc2734** [comment]
Basis には「タブ」とか「ドロワー」とか、最小のコンポーネントよりちょっと大きめのコンポーネントは入ってなくて（グリッドシステムはあるけど…）、それ単体を抜き出して使いたいという需要は無いだろうから、その需要は無視した構成にしたほうがシンプルで良さそうな気がしてきた。
